api_platform:
    title: 'Symfony REST API-BILMO '
    description: 'This Symfony API to manage a beautiful Bilmo catalog.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 3600
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization', 'Origin']
        public: true
